name = "mug"
version = "0.1.0"

description = "A TCP client for Gleam!"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "mug" }
links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.31"
gleam_erlang = "~> 0.22"

[dev-dependencies]
gleeunit = "~> 0.10"
glisten = "~> 0.8"
gleam_otp = "~> 0.7"
